# PermissionsBukkit configuration file
# 
# A permission node is a string like 'permissions.help', usually starting
# with the name of the plugin. Refer to a plugin's documentation for what
# permissions it cares about.
# Each node should be followed by true to grant that permission or false to
# revoke it, e.g. 'permissions.help: true'.
# Some plugins provide permission nodes that map to a group of permissions -
# for example, PermissionsBukkit has 'permissions.*', which can grant/revoke
# all admin permissions at once.
# 
# Users inherit permissions from the groups they are a part of. If a user is
# not specified here, or does not have a 'groups' node, they will be in the
# group 'default'. Any permissions specified for individual users will
# override their group permissions.
# World-specific permissions can be assigned with a 'worlds:' entry.
# 
# Groups can also inherit permissions from other groups. Like user
# permissions, groups may override the permissions of their parent group(s).
# Unlike users, groups do NOT automatically inherit from default.
# World permissions can also be assigned to groups with a 'worlds:' entry.

users:
  Notch:
    permissions:
      permissions.example: true
    groups:
    - admin
groups:
  default:
    permissions:
      permissions.example: false
  admin:
    permissions:
      permissions.*: true
    inheritance:
    - user
  user:
    permissions:
      permissions.example: true
    worlds:
      creative:
        coolplugin.item: true
    inheritance:
    - default

debug: false