name: PermissionsBukkit
main: com.platymuus.PermissionsBukkit.PermissionsPlugin
authors: [SpaceManiac, warriordog, EvModder]
website: https://github.com/EvModder/PermissionsBukkit
description: An optimized permission management plugin.
#3=ripped out setgroup (we have add/remove group) and setrank (replaced with dynamic group add/remove perms), reworked tab complete, various optimizations
#3.1=PlayerCommandSend - filter what commands players see (requires 1.13+), improved cmd usgage, various optimizations
version: 3.1
api-version: 1.13

commands:
  permissions:
    aliases: [perm]
    description: Permission related commands.
    permission: permissions.command
    usage: |
        /<command> reload - reload the configuration from disk.
        /<command> about - display general information on the plugin.
        /<command> check <perm> [player] - check if a player has a perm.
        /<command> info <perm> - print info for a specific perm.
        /<command> dump [player] [page] - print list of a player's perms.
        /<command> group - group related commands.
        /<command> group list - list all groups.
        /<command> group players <group> - list players in a group.
        /<command> group setperm <group> <[world:]perm> [true|false] - set a permission on a group.
        /<command> group unsetperm <group> <[world:]perm> - unset a permission on a group.
        /<command> player - player related commands.
        /<command> player groups <player> - list groups a player is in.
        /<command> player addgroup <player> <group> - add a player to a group.
        /<command> player removegroup <player> <group> - remove a player from a group.
        /<command> player setperm <player> <[world:]perm> [true|false] - set a permission on a player.
        /<command> player unsetperm <player> <[world:]perm> - unset a permission on a player.

permissions:
  permissions.*:
    default: op
    description: Allows use of all PermissionsBukkit administration commands.
    children:
      permissions.reload: true
      permissions.about: true
      permissions.check: true
      permissions.info: true
      permissions.dump: true
      permissions.group.*: true
      permissions.player.*: true

  permissions.command:
    description: Allows use of /permissions.

  permissions.reload:
    description: Allows use of /permissions reload.
    children: [permissions.command]

  permissions.about:
    description: Allows use of /permissions about.
    children: [permissions.command]

  permissions.check:
    description: Allows use of /permissions check.
    children: [permissions.command]

  permissions.info:
    description: Allows use of /permissions info.
    children: [permissions.command]

  permissions.dump:
    description: Allows use of /permissions dump.
    children: [permissions.command]

  permissions.group.*:
    description: Allows use of all /permissions group commands.
    children:
      permissions.group.list: true
      permissions.group.players: true
      permissions.group.setperm: true
      permissions.group.unsetperm: true

  permissions.group.list:
    description: Allows use of /permissions group list.
    children: [permissions.command]

  permissions.group.players:
    description: Allows use of /permissions group players.
    children: [permissions.command]

  permissions.group.setperm:
    description: Allows use of /permissions group setperm.
    children: [permissions.command]

  permissions.group.unsetperm:
    description: Allows use of /permissions group unsetperm.
    children: [permissions.command]

  permissions.player.*:
    description: Allows use of all /permissions player commands.
    children:
      permissions.player.groups: true
      permissions.player.addgroup: true
      permissions.player.removegroup: true
      permissions.player.setperm: true
      permissions.player.unsetperm: true

  permissions.player.groups:
    description: Allows use of /permissions player groups.
    children: [permissions.command]

  permissions.player.addgroup:
    description: Allows use of /permissions player addgroup.
    children: [permissions.command]

  permissions.player.removegroup:
    description: Allows use of /permissions player removegroup.
    children: [permissions.command]

  permissions.player.setperm:
    description: Allows use of /permissions player setperm.
    children: [permissions.command]

  permissions.player.unsetperm:
    description: Allows use of /permissions player unsetperm.
    children: [permissions.command]